# Generated by Django 5.1.2 on 2024-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=40)),
                ('subtitle', models.CharField(max_length=255)),
                ('hero', models.ImageField(upload_to='')),
            ],
        ),
    ]
