# Generated by Django 5.1.2 on 2024-10-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='hero',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
