# Generated by Django 5.1.2 on 2024-11-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('reference_code', models.CharField(blank=True, max_length=12, null=True)),
                ('amount', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='books.booksmodel')),
            ],
        ),
    ]
