# Generated by Django 5.1.2 on 2024-10-11 14:26

import books.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover', models.ImageField(upload_to=books.models.book_image_path, verbose_name='Book Cover Page Image')),
                ('title', models.CharField(max_length=32)),
                ('price', models.FloatField(default=0.0)),
                ('subtitle', models.CharField(max_length=64)),
                ('description', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
